### ISSUE TITLE
Chef Client Service not starting after reboot on Windows

### ISSUE THREAD

**Issue by docwhat** [chef/chef#2814]
On a windows system whenever it reboots, the chef client service isn't started.

Specs:
- Windows 2012 (no release packs)
- Chef 12.0.3

The Eventlog says:

```
A timeout was reached (30000 milliseconds) while waiting for the Chef Client Service service to connect.
```

There is nothing in the `chef-stacktrace.out` file.

I tried changing it to "Automatic (Delayed)" but it didn't fix whatever is going wrong.

I'm happy to help troubleshoot this, if you can give me steps to check or try.

**Comment by docwhat** [comment]
If it helps, I think this problem existed in chef 11 too.  But I've only been able to figure it out now that Chef 12 reports start and stop to the EventLog.

**Comment by docwhat** [comment]
This applies to Windows 2008R2 and Windows 2012R1 as well.

**Comment by galenemery** [comment]
@docwhat I ran into this issue today, but switching to delayed start is working as a workaround on 2008 and 2012.

Can you verify you're seeing the same behavior when using delayed start?

**Comment by docwhat** [comment]
I manually changed it, rebooted, and I got the same message on win 2012

**Comment by joelwilson** [comment]
This issue bit me. I can confirm that changing the startup type to `Automatic (Delayed Start)` seems to resolve the problem on Windows 2012 R2.

**Comment by alexpop** [comment]
I've also bumped into this in AWS(2012R2) w/ chef-client 12.0.0 - 12.0.3

EventLog shows:
```
The Chef Client Service service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.
```

The workaround of changing from 'Automatic' to 'Automatic (Delayed start)' worked for me also on 2012R2.

This is the Chef resource to use in order to change the startup type until this issue is resolved:

```
registry_key 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\chef-client' do
  values [{
    :name => "DelayedAutostart",
    :type => :dword,
    :data => 1
  }]
  action :create
end
```

**Comment by alex-williams** [comment]
I've hit this too. Using the latest Chef-Client, built from Master some time last week. Unfortunately, the resource code my good man Mr Pop has put above, does create the registry key, but doesn't actually start my client service upon reboot. Manually starting the service, completes my chef-client run appropriately.

**Comment by alex-williams** [comment]
Not absolutely positive here, but changing

DelayedAutostart to DelayedAutoStart - (Notice the capital S)

Appears to have fixed this, at least for me. I thought Windows and the registry were case insensitive.

**Comment by vvchik** [comment]
Hi, this workaround doesnt work for me, any idea to find root cause?
server win2012r2 (Platform:    windows 6.3.9600)
chef-client - 12.2.1 
service starting well if i run it in manual mode but falling to start after server restart

**Comment by alex-williams** [comment]
I continually had this working in my last project, with the work-around, but it was with Win2012 R1, not R2, I'm unsure if R2 somehow breaks the work-around. My current project is using Win2008, so I may not get the chance to test this either.

**Comment by vvchik** [comment]
well, my investigations continuing, we are using hyper-v, and vlans
so far we tested that chef-client as service successfully starts on virtualbox and hyper-v without vlan configuration. But when we turn it on and reboot server chef-client isn't starts.

**Comment by alex-williams** [comment]
This appears fixed for me in the latest Chef-Client. At least on Win 2008 R2, which is one of the systems people have complained about this bug with, the latest Chef-12.2.1-1 client appears to be setting itself to Automatic(Delayed Start) without my intervention.

**Comment by spuder** [comment]
I am a coworker of vvchik and I can reproduced this. 

The chef client starts automatically when there is *no* network connectivity on Windows 2012r2 
As soon as we connect the network, then the chef client fails to start by itself. 

The variable that makes the difference is network connectivity. 

Chef 12.2.1.1

![screenshot 2015-04-17 15 56 57](https://cloud.githubusercontent.com/assets/242382/7212563/76950282-e526-11e4-9988-2c08337b5d24.png)


There is a stacktrace.out file that is generated 

```
Generated at 2015-04-17 18:19:10 -0400
SocketError: Error connecting to https://foobar.example.com/organizations/dev/nodes/host01 - getaddrinfo: No such host is known.
C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:878:in `initialize'
C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:878:in `open'
C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
C:/opscode/chef/embedded/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:877:in `connect'
C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:851:in `start'
C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:1367:in `request'
C:/opscode/chef/embedded/apps/chef/lib/chef/http/basic_client.rb:65:in `request'
C:/opscode/chef/embedded/apps/chef/lib/chef/http.rb:261:in `block in send_http_request'
C:/opscode/chef/embedded/apps/chef/lib/chef/http.rb:293:in `block in retrying_http_errors'
C:/opscode/chef/embedded/apps/chef/lib/chef/http.rb:291:in `loop'
C:/opscode/chef/embedded/apps/chef/lib/chef/http.rb:291:in `retrying_http_errors'
C:/opscode/chef/embedded/apps/chef/lib/chef/http.rb:255:in `send_http_request'
C:/opscode/chef/embedded/apps/chef/lib/chef/http.rb:142:in `request'
C:/opscode/chef/embedded/apps/chef/lib/chef/rest.rb:115:in `get'
C:/opscode/chef/embedded/apps/chef/lib/chef/node.rb:499:in `load'
C:/opscode/chef/embedded/apps/chef/lib/chef/node.rb:483:in `find_or_create'
C:/opscode/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:92:in `load_node'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:233:in `load_node'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:435:in `run'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:365:in `run_application'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:63:in `load'
C:/opscode/chef/bin/chef-client:63:in `<main>'
```
The chef service *will* start and stay running if you open services.msc and click the start button. Even when there is internet connectivity. 

### Service Order

I've verified that the windows machine can resolve 'foobar.example.com'. 

jaym in the IRC Chanel theorizes that the chef client is starting before the DNS service. I've added the following dependencies to the chef-client. (The space is required after `depend=`) 

    sc config chef-client depend= LanmanServer/Dnscache

This had no luck. After 2 minutes, the chef-client service tried to start, but failed. No stacktrace was generated. I was able to start the process manually by clicking 'start' in services.msc

### Event Viewer

The only thing that the event viewer shows is " A timeout was reached (30000 milliseconds ) while waiting for the chef client to start". 

Interestingly, if I reboot the VM and quicky attempt to start the chef process manually, I get this error. 

![screenshot 2015-04-17 18 10 23](https://cloud.githubusercontent.com/assets/242382/7212949/20a0155e-e52d-11e4-969f-efc914be446c.png)

Surprisingly, if I wait 2 minutes, the chef process will start by itself. Attempting to start the process manually (even though it fails) appears to "dislodge" whatever was stopping the service from starting itself. 

I've also tried setting the service to recover itself 2 more times after 1 minute, Strangely, windows did not honor this setting and gave up after one attempt. 

![screenshot 2015-04-17 18 17 45](https://cloud.githubusercontent.com/assets/242382/7213026/356fa4fc-e52f-11e4-8623-cccb508a89ca.png)

The bug is likely in this code, however I am at a loss of how to further troubleshoot this problem. 
https://github.com/chef/chef/blob/master/lib/chef/application/windows_service.rb

**Comment by skyguy94** [comment]
After updating my bootstrapping scripts (cloudformation) to install chef-client 12.3.0-1 instead of 11.16.4-1, I'm seeing the same error as the dialog above (Error 1053: ...). In troubleshooting the issue, I noticed that the *Path to executable* in the service config is:
"C:\opscode\chef\embedded\bin\ruby" "C:\opscode\chef\embedded\lib\ruby\gems\bin\chef-windows-service"  -c C:\chef\client.rb -L C:\chef\log\client.log

When I look for these things on the filesystem, I see that *chef-windows-service* is located in:
C:\opscode\chef\embedded\lib\ruby\gems\_2.0.0_\bin

Comparing this to an older instance running chef-client 11.16.4-1 I see:

"C:\opscode\chef\embedded\bin\ruby" "C:\opscode\chef\embedded\lib\ruby\gems\_1.9.1_\gems\chef-11.16.4-x86-mingw32\lib\chef\application\windows_service.rb"  -c C:\chef\client.rb -L C:\chef\log\client.log

It looks as if some PR has borked out the version. I'm not sure how to reconcile this with the workarounds and spontaneous fixes mentioned above as I can't see how the path would be corrected.

**Comment by spuder** [comment]
We worked around it by specifying an older version of chef while bootstrapping. 

    knife bootstrap --bootstrap-version 11.xx

**Comment by skyguy94** [comment]
Falling back to the 12.2.1-1 msi fixes the issue for me.

**Comment by thommay** [comment]
ping @chef/client-windows

**Comment by btm** [comment]
@thom we'll pull it into our committed lane next week.

**Comment by btm** [comment]
For those still having issues, please try this workaround: `sc.exe config chef-client depend= dnscache` and report back.

**Comment by bigbam505** [comment]
I tried this first with the default install of the chef-client service and then with the dependency set.  Both failed on startup.  The only way this works for me is if the Delayed Start option is selected.  I am running Windows Server 2008 R2 for reference.  In addition there are no logs anywhere to show what the error is

**Comment by btm** [comment]
@bigbam505 what version of Chef are you using? Delayed Start became the default in https://github.com/chef/omnibus-chef/pull/346, which based on the date it was merged would have been in Chef 12.1.0. /cc @jdmundrawala.

I'm trying to get my Server 2012 VM to not boot so fast. It's annoyingly difficult.

**Comment by bigbam505** [comment]
@btm I am running chef client 12.2.1

**Comment by btm** [comment]
@bigbam505 I downgraded to 12.2.1 and confirmed the service was created as Delayed Start. If that works for you as a workaround, that's great. 

The complete solution is likely to identify a service we can depend on, as I mentioned Delayed Start is a timer which is arbitrary and won't work in some cases. I'll keep looking.

**Comment by bigbam505** [comment]
Interesting.  We install the service with chef itself using the chef-client cookbook.  This just calls the chef-service-manager [Here](https://github.com/opscode-cookbooks/chef-client/blob/master/recipes/windows_service.rb#L33).  Looking at the chef-service-manager it looks like it does not use the delayed start of the service unless I am missing something.  Here is the code for the chef-service-manager [here](https://github.com/chef/chef/blob/8b37ebb3468879477fbeeba9511c10a00d530b97/lib/chef/application/windows_service_manager.rb#L115-L126)

**Comment by bigbam505** [comment]
Actually this is why.  The chef-service-manager does not use delayed, however the installer does https://github.com/chef/omnibus-chef/blob/master/resources/chef/msi/source.wxs.erb#L49-L60

**Comment by ksubrama** [comment]
@spuder @vvchik The issue due to VLAN might be related or might be independent - it seems that DNS resolution very early on is failing for some reason but that might not be related to the timeouts others are seeing.  For others who still see "A timeout was reached", could you follow steps in https://support.microsoft.com/en-us/kb/824344 to set ServicesPipeTimeout under HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control to some long time (say 2 hours or something along those line)?  If it starts working, that would imply that our service startup is being slow for some reason.  The reason for the poor logging involved is because the service is getting killed for before logging has been set up.

**Comment by GregAndo** [comment]
Okay, so I have performed a significant amount of investigation into this issue, and I believe we are potentially seeing multiple issues here.  Firstly, a performance issue.  I have found in our test environment (which isn't the fastest environment in the world) that the first time I execute chef-client after a reboot and from the command line, it can literally take over 30 seconds to even return any kind of response (IE "Starting Chef Client, version 12.4.1").  If this is significantly less than 30 seconds, you may never see this issue.  If it is around 30 seconds, you may see the service intermittently starting with the above error randomly.  If it is well over 30 seconds (in my case 45-55 seconds) you will likely always see this error.  I am not sure why chef-client takes so long to initialise the first run, but subsequent runs are usually much quicker in the environment I am using to test.  Thus far in my case, I have needed to extend the ServicesPipeTimeout to 60 seconds to give the service long enough to start.

However, even this may not be enough.  The chef-client environment is dependent on the service "Windows Management Instrumentation" or "Winmgmt".  You can confirm this by stopping the chef-client service (and any other running instances of chef-client), setting the Winmgmt service to disabled, and then attempting to run chef-client from the command line: it will fail.  In my case, this was the primary issue I was seeing here - and the chef-client didn't seem to fail gracefully - it would just hang.  The longer you set the timeout for ServicesPipeTimeout - the longer it would be hung before Windows killed it, and it seemed to delay other services from starting also (I assume Windows only starts one service at a time).

So it seems to me that the service is being installed incorrectly by the chef-client recipe so far as it is not supplying the service the correct dependencies (Winmgmt) when installing the service.  There are multiple ways to modify this as a work around:  either using the "sc.exe" command ("sc.exe config chef-client depend= Winmgmt")(definitely note there is a space after the depend=).  Alternatively, you could create a recipe that adds a REG_MULTI_SZ (Multi String Value) to the registry (at your own risk) under HKLM\SYSTEM\CurrentControlSet\Services\chef-client which you would name "DependOnService" and for the value you would add a single row of text "Winmgmt" without the quotes.  The dependency should take effect from the next reboot of the server.  This will force the Windows to wait until it's dependent service is running before it attempts to start the chef-client service, and should allow you to more accurately identify the amount of time required for the chef-client service to start correctly.  One way to do this may be by temporarily extending the ServicesPipeTimeout value as described above, stopping the chef-client service, setting it to manual start, restarting Windows, and then manually timing how long the service takes to start.  This (with some extra time for fluctuations) would be your new value for ServicesPipeTimeout.

In my opinion, the service start time for chef-client needs a significant reduction to be feasible in an enterprise environment.  I think it also needs to fail more gracefully, and do so in an automated fashion within 25 seconds, and hopefully with some logging.  I am not sure how much luck we will have with that.

@spuder did some nice work there, and seemed to get pretty close.  I think the recovery does not work because the service never successfully started to begin with.  I am of the opinion that if the service started returned success but the failed later, Windows would attempt to restart.  I am not sure what your specific issue is/was, but if I had to guess, maybe something is shutting down your Winmgmt service once network connectivity is available?

I hope someone finds this useful.  Would appreciate any feedback!

**Comment by docwhat** [comment]
@GregAndo - Amazing debugging there!

Do we know how Windows is detecting if the program is working?  Is it looking for output? Or is it something else (e.g. an internal state in the Kernel process table)?

Would it help with the long start up by calling a `.cmd` or `.ps1` script instead and have that run `ruby`?  That way the script is marked as running quickly and then Ruby can take longer to start?

I'm thinking Ruby isn't loading quickly because it gathers lots of files (both `.rb` and `.dll`) to run `chef-client`.  Windows is slow at opening lots of little files and with a busy disk (due to startup) and a very cold cache it is expected a complicated Ruby program would take a while to start.

**Comment by ksubrama** [comment]
@GregAndo Hey, thanks for that!  I am adding Winmgmt to the list of dependencies for chef-windows-service.  That service is supposed to be automatically launched when WMI is invoked (and we invoke WMI to figure out which version of windows we're on - there's not much else we can do before that).  Also, the startup time for the actual chef-client run is different from the startup time for the service itself.  There may very well be some reason our ruby startup is taking a while but I'm having a hard time reproducing it.

As for chef-client itself taking a long time to start up - I agree that that's too long but that might be a separate issue (ohai takes a while to startup, plugins need to be loaded...  etc.).

**Comment by ksubrama** [comment]
@docwhat For a service, it has strict rules.  A service needs to broadcast that it's in the running state within 30 seconds of startup (that time is overriden by ServicesPipeTimeout).  We run https://github.com/chef/chef/blob/master/lib/chef/application/windows_service.rb#L63 (and initialization) - so not a lot except for initializing logging.  My primary suspicion here is that ruby is taking a while to launch and collect the gems involved but I can't seem to reproduce it with on 12.4.1 using a fresh chef-client installation.  That is unless your client.rbs all contain extremely weird and end-case triggering options - like putting your config file online (we open up a web client to download the config), or your config file is on a network drive or a hyper-v shared drive (we block to open the file) or something else like that.

**Comment by docwhat** [comment]
Can you send the "I'm up" message before doing a full `require "chef"`?  On my blazing fast SSD MacBook that require takes about 3 seconds (not measured). 

Though that doesn't really explain 30 seconds and would probably hide the problem. 

Is there a way we can profile it? I'd be happy to create a VM here to run a profiling version of Chef or Ruby.

I'm not a windows person so I'm not familiar with the toolset.

**Comment by lamont-granquist** [comment]
Can someone validate if chef/omnibus-chef#440 fixes this or not?

**Comment by smurawski** [comment]
Just run in a scheduled task.

**Comment by alexpop** [comment]
I can @lamont-granquist. Is chef-client 12.4.3 a good build for that?

**Comment by ksubrama** [comment]
@alexpop You need a 12.5 nightly I believe.

**Comment by troyready** [comment]
@ksubrama @alexpop fwiw, I see the referenced commited tagged in 12.4.3

**Comment by JaminShanti** [comment]
The fix is "sc.exe config chef-client depend= Winmgmt"

If you want to fix them all,
$list = @" 
server1
server2
server3
"@ -split "`n" | % { $_.trim() }

$serviceAccount = Get-Credential

$serverlist = foreach ($server in $list){ Invoke-Command -ComputerName $server -credential $serviceAccount -ScriptBlock { sc.exe config chef-client depend= Winmgmt; start-service chef-client} }
$serverlist

**Comment by alexpop** [comment]
I have a Windows 2012R2 VirtualBox VM where I'm seeing the Chef Client Service(version 12.4.1) not starting after reboot using "Automatic" Startup Type. Changing that to "Automatic (Delayed Start)" makes the service start a few minutes after boot.

I've now installed a chef-client 12.5 nightly build which uses "Automatic (Delayed Start)" by default. I switched that to "Automatic" and the Chef Client Service is starting fine after reboot. 

Is it safe to default back to "Automatic" in order to avoid the delayed start?

**Comment by johnsmyth** [comment]
It looks like the fix appears in the commit tagged [12.4.2] (https://github.com/chef/omnibus-chef/blob/chef-12.4.2/resources/chef/msi/source.wxs.erb#L69) but the released chef-client versions 12.4.2 and 12.4.3 don't seem set the dependency.  I'm sure I'm missing something obvious, but how can I tell what version it is (will be?) fixed in?

**Comment by dovreshef** [comment]
I'm still seeing the error on Windows 2012 R1 VMs built on Azure.
Running chef-client version 12.5.1.
It appears as though startup type is already set to "Automatic (Delayed Start)", and Winmgmt is a dependency.

```
PS C:\Users\***> get-item -path "HKLM:\SYSTEM\CurrentControlSet\Services\chef-client"


    Hive: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services


Name                           Property                                                                                                            
----                           --------                                                                                                            
chef-client                    Type             : 16                                                                                               
                               Start            : 2                                                                                                
                               ErrorControl     : 0                                                                                                
                               ImagePath        : c:\opscode\chef\embedded\bin\ruby.exe C:\opscode\chef\bin\chef-windows-service                   
                               DisplayName      : Chef Client Service                                                                              
                               DependOnService  : {Winmgmt}                                                                                        
                               ObjectName       : LocalSystem                                                                                      
                               Description      : Runs Chef Client on regular, configurable intervals.                                             
                               DelayedAutostart : 1        
```

Setting ServicesPipeTimeout to a large value helped.

**Comment by joshoohaah** [comment]
also seeing this in AWS for Win2012 R1 and R2 images.

**Comment by dparkar** [comment]
I can repro this on Windows Server 2012 with Chef Client version 12.5.1, but it seems to work fine on Windows Server 2012 Data Center.

**Comment by tas50** [comment]
I'm going to close this out at this point since we recommend users not setup chef as a service. The preferred route is a task since that avoids the long running ruby task and ruby on windows memory leaks.
