### ISSUE TITLE
Add deprecation warning when passing provider argument to package resource and point users at declare_resource

### ISSUE THREAD

**Issue by aroeber-kovarus** [chef/chef#5350]
## Description

Using the rpm_package process with options set system is ignoring options and failing to do expected process. Expected out put is to install the package regardless of what is there or not from the --force option call.
## Chef Version

chef-client  ==   Chef Client, version 12.13.37
## Platform Version

OS   ==   CentOS Linux release 7.2.1511 (Core)
## Replication Case

install the updated kernel (kernel-3.10.0_DEVMEM_DISABLED-1.x86_64.rpm), reboot to have take affect. use chef to install header for other application installation.
cookbook::recipe has the following:

```
rpm_package 'kernel-headers-3.10.0_DEVMEM_DISABLED-1.x86_64.rpm' do
   provider Chef::Provider::Package::Rpm
   source 'http://somesystem.internal/repodir/kernel-headers-3.10.0_DEVMEM_DISABLED-1.x86_64.rpm'
   options '--force'
   action :install
end
```

Check of system show package not installed:
yum list installed | grep kernel-headers-3.10.0_DEVMEM_DISABLED-1
yum list installed | grep kernel-headers-3.10.0
yum list installed | grep kernel-header
      kernel-headers.x86_64              3.10.0_DEVMEM_DISABLED-1           installed
Returns: No matching Packages to list
## Client Output

Recipe: initial_deployer::kernal_mod
- rpm_package[kernel-headers-3.10.0_DEVMEM_DISABLED-1.x86_64.rpm] action installkernel-headers 3.10.0_DEVMEM_DISABLED-1
  kernel-headers 3.10.0_DEVMEM_DISABLED-1
  (up to date)
## Captured logs
# The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

[2016-09-20T13:37:38-07:00] INFO: Processing rpm_package[kernel-headers-3.10.0_DEVMEM_DISABLED-1.x86_64.rpm] action install (initial_deployer::kernal_mod line 30)
[2016-09-20T13:37:38-07:00] DEBUG: rpm_package[kernel-headers-3.10.0_DEVMEM_DISABLED-1.x86_64.rpm] checking rpm status
[2016-09-20T13:37:38-07:00] DEBUG: rpm_package[kernel-headers-3.10.0_DEVMEM_DISABLED-1.x86_64.rpm] checking install state
[2016-09-20T13:37:38-07:00] DEBUG: rpm_package[kernel-headers-3.10.0_DEVMEM_DISABLED-1.x86_64.rpm] current version is 3.10.0_DEVMEM_DISABLED-1
[2016-09-20T13:37:38-07:00] DEBUG: rpm_package[kernel-headers-3.10.0_DEVMEM_DISABLED-1.x86_64.rpm] kernel-headers-3.10.0_DEVMEM_DISABLED-1.x86_64.rpm 3.10.0_DEVMEM_DISABLED-1 satisifies 3.10.0_DEVMEM_DISABLED-1 requirement
[2016-09-20T13:37:38-07:00] DEBUG: rpm_package[kernel-headers-3.10.0_DEVMEM_DISABLED-1.x86_64.rpm] is already installed - nothing to do
## Stacktrace

None found no error indicated from chef,
### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.
- [Server issues](https://github.com/chef/chef-server/issues/new)
- [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
- Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by aroeber-kovarus** [comment]
Updated info on how process is run:
Kernel is updated and rebooted then this set of steps are run:
yum -y install https://packages.chef.io/stable/el/7/chef-12.13.37-1.el7.x86_64.rpm
yum -y install git
git clone https://github.com/somerepo/kernel-development.git
move into cookbook directory
chef-client -l debug -L /tmp/chef.kernal_mod.log -z -o 'initial_deployer::kernal_mod' -N `hostname -s`

**Comment by aroeber-kovarus** [comment]
More to update changed the resource from rpm_package to package:
The bug is only in the rpm_package resource and it appears uses a different provider then the package resource.
When the provider is called the same way, “provider Chef::Provider::Package::Rpm” in both resources,
it only works as expected in the the package resource.

**Comment by aroeber-kovarus** [comment]
Another update
Moving to the next package the resource package is not using the provider call to lock the process in place.
recipe:
```package 'kernel-3.10.0_DEVMEM_DISABLED-1.src.rpm' do
   provider Chef::Provider::Package::Rpm
   source 'http://sau2658-ocures-adm-01.sau2658.thefacebook.com/bigsur/kernel-3.10.0_DEVMEM_DISABLED-1.src.rpm'
   options '--force'
   action :install
end
```
chef-client out put NOTE yum_package call not rpm -- not what is expected.
 * yum_package[kernel-3.10.0_DEVMEM_DISABLED-1.src.rpm] action installkernel 3.10.0_DEVMEM_DISABLED-1
kernel 3.10.0-327.el7
kernel 3.10.0_DEVMEM_DISABLED-1
 (up to date)

**Comment by lamont-granquist** [comment]
So --force as an option makes little sense to chef-client, since we always do an idempotency check.   If you really want to force install it every single time, then it makes more sense to just use an execute resource to dispatch the command.

**Comment by aroeber-kovarus** [comment]
So then why does it have the options tool available if it is not going to be used?
The --force is used because the provider called is rpm and Chef is using yum (see the logs)
If the resource is going to do something different then what I am requesting then what have the ability to call provider with an options in the resource at all?

**Comment by lamont-granquist** [comment]
So fundamentally you want to install this package:

```
rpm_package 'kernel-headers-3.10.0_DEVMEM_DISABLED-1.x86_64.rpm' 
```

And you already have that package installed?

```
yum list installed | grep kernel-header
kernel-headers.x86_64 3.10.0_DEVMEM_DISABLED-1 installed
```

That is exactly how the rpm_package and yum_package providers work.  It has no other way of knowing that the package is in some way updated or different.  Generally packaging updated artifacts with the same version number is a really bad practice and the version of the updated package should have been bumped.

If you really want to do this then just use an execute resource:

```
execute "rpm -ivh --force 'http://sau2658-ocures-adm-01.sau2658.thefacebook.com/bigsur/kernel-3.10.0_DEVMEM_DISABLED-1.src.rpm'"
```

That will run every time you run chef-client, though, which is unavoidable because there's no way to determine that upgraded version of the package isn't installed as far as i can see.

You'll probably need to include a not_if/only_if guard of some kind there, but I can't see how it should be written based on the information here.

**Comment by aroeber-kovarus** [comment]
Yes the kernel was installed via YUM with an upgrade, that broke the system as the kernel needs to be installed with a rpm install, that is why the call to rpm_package was used.
Chef logic is ignoring the direct call to rpm install and is using yum upgrade.
WHY is it doing this?
YES, doing the execute is a work around, as was the --force and the use of provider both in rpm_package and package resource.
YES calling a direct version is not best practice, but so is ignoring a direct call to a document resource.

**Comment by lamont-granquist** [comment]
if you do `package "foo"` on redhat with an explicit `provider` to the yum provider you'll wind up with a Chef::Resource::YumPackage given to you by the resource resolver wrapping a Chef::Provider::Package::Rpm class that does the implementation work.   the output will say `yum_package` which comes from the resource that you used.  its misleading, but (mostly) probably worked.  i don't understand why you tried doing that.   in chef-11 you would get a Chef::Resource::Package base class wrapping the RPM provider but that was worse overall because the extra validation in the Chef::Resource::RpmPackage class was missing whenever anyone used `package "foo"`.  in chef-12 `package "foo"` works correctly without a provider while giving the provider option is differently broken from what happened with chef-11.  you should just use `rpm_package`.

if rpm_package is calling yum then that would be a bug, but i don't see anything in your output to indicate it does.

**Comment by aroeber-kovarus** [comment]
OK, then I would ask you to look at this again:
I state in my initial test I am calling rpm_package.
I then added to rpm_package the `provider Chef::Provider::Package::Rpm`
Then I show the recipe with the call to package with `provider Chef::Provider::Package::Rpm`
This call should have installed the package, but did not because it shifted to YUM and that output I believe I showed in my comment 3 hour ago where the chef output shows it is doing a YUM call.
I have confirmed ALL of this with the checks of `yum list installed` and `rpm -qa` also shown

**Comment by lamont-granquist** [comment]
again:

- use `rpm_package`
- do not use the provider argument with `rpm_package`
- never, ever try to use the provider argument with `package`

the latter pattern was always buggy in chef, and was made deliberately buggier in chef-12 because it could not be salvaged (by the time you are parsing the provider argument you've had to create the resource object to instance_eval the block to, and since the parser cannot guess what provider argument you'll eventually pass to the block, at the time we create the resource we have to guess and chef-12 guesses so that `package "foo"` is fixed, but which has the side effect of making the behavior when passing a provider even worse such that you see the "yum_package" in the output but the underlying provider is a package provider and you're getting yum_package validation over the top of rpm_package behavior, which is horrible).

there's literally no way to code around this.  the correct way to install an rpm package is with `rpm_package`.

we can't fix this, literally because of constraints of the parser and the ruby language.  but there's nothing here which fundamentally does not work.  the correct, and simplest, way to invoke the rpm package provider is with `rpm_package`.

**Comment by thommay** [comment]
As Lamont says, you need to use `rpm_package` directly, rather than `package` with a specified provider. We'll add some warnings to chef and foodcritic to make it plain that this won't work as one might expect.

**Comment by lamont-granquist** [comment]
Well, package resource never allowed the provider to be specified sanely and fundamentally can't...

So, yeah we can throw a deprecation warning when users try to pass the provider argument to the rpm_package resource and point them towards declare_resource.

**Comment by aroeber-kovarus** [comment]
Thank you, and now that I am not neck deep in dealing with this the main issue is still that calling rpm_package is using a yum process to upgrade packages, and not using rpm process to install as needed.
Yum upgrade has been removing the old kernel and support components, not installing the new components as required by this process.
My work around was to use execute and the direct rpm command.

**Comment by tas50** [comment]
Added an issue in cookstyle to get a cop for this here: https://github.com/chef/cookstyle/issues/291

**Comment by tas50** [comment]
Closing this out since we should tackle this with cookstyle instead
