### ISSUE TITLE
Chef Infra 15: No "cookbooks" attribute passed back to Chef Infra Server

### ISSUE THREAD

**Issue by coding-blip** [chef/chef#8817]
## Description
I did a search online and asked on the Slack channel about this issue. I also skimmed briefly through the diff files with a member from the Slack channel and compared between the 2 versions I am having issues with.

I am trying to find out if something has changed in Chef Infra 15 with some of the attributes being passed back to the Chef Infra server. We have a cookbook that relies on searching attributes on the Chef Server for the node['cookbooks'] attribute to see if a node is running a specific cookbook. Was this removed in Chef Infra 15 as I can not see the "cookbooks" attribute on any of my Chef 15 nodes, but can on my Chef 14 nodes.

For further context when running chef-shell --client and switching to attributes_mode and doing node.cookbooks I am able to see the cookbooks applied to the node, but again they are not passed back to the Chef server on Chef client run completion.

Is this an intended consequence of Chef Infra 15? I was not able to find anything in the release notes about it?

## Chef Version
Chef Client 14.13.11 (works)
Chef Client 15.1.36 (doesn't work)
Chef Client 15.2.20 (doesn't work)

## Platform Version
All of the clients we have running Chef 15 right now are RHEL 7.6 and RHEL 7.7.

## Replication Case
Run Chef Client 14, see expected "cookbooks" attribute. Run Chef Client 15 don't see the "cookbooks" attribute.

## Client Output
chef-shell --client and switching to attributes_mode and doing node.cookbooks I am able to see the cookbooks applied to the node, but again they are not passed back to the Chef server on Chef client run completion.

**Comment by lamont-granquist** [comment]
That certainly isn't an intended effect, but at the same time we didn't touch any code that would have directly affected that.  The fact that you can see them applied to the node in chef-shell suggests more of a config problem on your side.

Note that if you have whitelist/blacklists configured that we fixed bugs in that so that they work properly now:

https://github.com/chef/chef/pull/8396/commits/0656a02111ad32ccccdc92e29d53a32b2c8dd66e

**Comment by coding-blip** [comment]
Unfortunately, we are not using any sort of whitelist or blacklist for our attributes. We are setting up some of the lines in our config.rb with the chef-client cookbook. Here is a sample below of the config.rb.
```
chef_license "accept"
chef_server_url "https://chef-server.fdqn/organizations/org_name"
client_fork true
log_location "/var/log/chef/client.log"
ssl_verify_mode :verify_none
validation_client_name "name-validator"
verify_api_cert false
node_name "node-name"

ohai.plugin_path << "/etc/chef/ohai/plugins"
```

Also of note, we are still getting all of the other attributes properly along with other attributes from the chef-server such as role, run_list and recipes.

**Comment by sean-horn** [comment]
@lamont-granquist I have reproduced the same here at Chef in Chef Infra Client 15.0.293 and 15.2.20 while 14.x works.

It's confusing, because the first thing I checked was the code here and it's still there https://github.com/chef/chef/blob/v15.2.20/lib/chef/node.rb#L87-L95

Here is output from the same node, same runlist, same /etc/chef/client.rb
The only thing changing is the rpm installation of the chef-client program

14.x `knife node show NODENAME -Fj -l` output

```
....other typical node data....

    "expanded_run_list": [
      "audit::default",
      "location_plugin::default",
      "test::default"
    ],
    "roles": [

    ],
    "cookbooks": {
      "audit": {
        "version": "7.8.0"
      },
      "location_plugin": {
        "version": "0.1.5"
      },
      "ohai": {
        "version": "5.1.0"
      },
      "test": {
        "version": "0.1.0"
      },
      "chef-ingredient": {
        "version": "2.3.0"
      }
    }
```

15.x `knife node show NODENAME -Fj -l` has no `cookbooks` data output

**Comment by coding-blip** [comment]
It is good that you were able to see the same issue on your end. This rules out that it is limited to just my setup and configuration. Any thoughts on what may be causing it?

**Comment by lamont-granquist** [comment]
There's code rearrangement in the policy_builder code here:

https://github.com/chef/chef/blob/v15.2.20/lib/chef/policy_builder/expand_node_object.rb#L77-L96

```
run_context.node = node
```

cannot be called before:

```
run_context.cookbook_collection = cookbook_collection
```

because set_cookbook_attribute is called as a side-effect of setting the node on the run_context (which is probably poor).
