### ISSUE TITLE
Multiple issues with launchd resource

### ISSUE THREAD

**Issue by erikng** [chef/chef#9788]
## Description
Moving away from the official plist gem to the built in provider ported from Microsoft has resulted in significant regressions moving from the latest stable Chef 15 to Chef 16.

I believe the issue is firmly due to https://github.com/chef/chef/pull/9642

Regressions found:
#### launchd idempotence
```
  * launchd[com.googlecode.munki.ManagedSoftwareCenter] action enable
    * file[/Library/LaunchAgents/com.googlecode.munki.ManagedSoftwareCenter.plist] action create (up to date)
    * macosx_service[com.googlecode.munki.ManagedSoftwareCenter] action restart
      - restart service macosx_service[com.googlecode.munki.ManagedSoftwareCenter]
```

#### Creating a launchd item fails due to 0kb files being created on disk with the plist module unable to read the data.
```
    * launchd[com.uber.chef.uberinternal.umad.agent] action enable
      * file[/Library/LaunchAgents/com.uber.chef.uberinternal.umad.agent.plist] action create
        - create new file /Library/LaunchAgents/com.uber.chef.uberinternal.umad.agent.plist
      * macosx_service[com.uber.chef.uberinternal.umad.agent] action restart
        
        ================================================================================
        Error executing action `restart` on resource 'macosx_service[com.umad.agent]'
        ================================================================================
        
        Mixlib::ShellOut::ShellCommandFailed
        ------------------------------------
        Expected process to exit with [0], but received '1'
        ---- Begin output of plutil -convert xml1 -o - /Library/LaunchAgents/com.umad.agent.plist ----
        STDOUT: /Library/LaunchAgents/com.umad.agent.plist: Property List error: Cannot parse a NULL or zero-length data / JSON error: No value.
        STDERR: 
        ---- End output of plutil -convert xml1 -o - /Library/LaunchAgents/com.umad.agent.plist ----
        Ran plutil -convert xml1 -o - /Library/LaunchAgents/com.umad.agent.plist returned 1

```

#### launchd cannot find the right service (it does not look to be honoring the `type` any longer, resulting in it finding "duplicate" service names.

```
    * launchd[com.somethingumad] action enable
      * file[/Library/LaunchAgents/com.something.umad.plist] action create (up to date)
      * macosx_service[com.umad] action restart
        * Several plist files match service name. Please use full service name.
        ================================================================================
        Error executing action `restart` on resource 'macosx_service[com.something.umad]'
        ================================================================================
        
        Chef::Exceptions::Service
        -------------------------
        Several plist files match service name. Please use full service name.
```

#### Launchd cannot find plist if it is in Apple's /System folder
```
Recipe: cpe_ssh_server::default
  * cpe_ssh_server[Configure SSH server] action manage
    * launchd[Disable SSH] action disable
      * macosx_service[Disable SSH] action disable
        * Could not find plist for macosx_service[Disable SSH]
        ================================================================================
        Error executing action `disable` on resource 'macosx_service[Disable SSH]'
        ================================================================================
        
        Chef::Exceptions::Service
        -------------------------
        Could not find plist for macosx_service[Disable SSH]
        
        Resource Declaration:
        ---------------------
        # In /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/provider/launchd.rb
        
        119:         macosx_service label do
        120:           name(label) if label
        121:           service_name(label) if label
        122:           plist(@path) if @path
        123:           session_type(session_type) if session_type
        124:           action(action)
        125:           only_if { manage_agent?(action) }
        126:         end
        127:       end
        
        Compiled Resource:
        ------------------
        # Declared in /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/provider/launchd.rb:119:in `manage_service'

```

## Chef Version
16.0.257

## Platform Version
macOS 10.15.4

## Replication Case
1. To replicate idempotence, run chef twice and you will notice it continues to `restart` launchd items.
2. To replicate issue 2, you can use this launchd resource
```
launchd 'com.googlecode.munki.ManagedSoftwareCenter' do
  label 'com.googlecode.munki.ManagedSoftwareCenter'
  limit_load_to_session_type ['Aqua']
  program_arguments [
    '/usr/local/munki/launchapp',
    '-a',
    '/Applications/Managed Software Center.app',
  ]
  keep_alive(
    { 'PathState' => {
      '/var/run/com.googlecode.munki.ManagedSoftwareCenter' => true,
    } },
  )
  run_at_load false
  type 'agent'
  action :enable
end
```
3. To replicate issue 3, it's recommend to use [cpe_umad](https://github.com/uber/cpe-chef-cookbooks/tree/master/cpe_umad) from Uber's cookbook github repo
4. To replicate issue 3, it's recommend to use [cpe_ssh_server](https://github.com/uber/cpe-chef-cookbooks/tree/master/cpe_ssh_server) from Uber's cookbook github repo

## Client Output
Posted above

## Stacktrace
I can provide more if needed and I am happy to help debug, but I believe this new plist resource is not complete enough to handle all of the edge cases that the official plist gem offers.

I do not think this PR was tested for regressions either.

**Comment by erikng** [comment]
@tas50 would really appreciate you looking into this one.

**Comment by tas50** [comment]
Thanks for the report @erikng. We're taking a look at the root cause now.

**Comment by tas50** [comment]
This should be fixed by #9812 which will be released asap.

**Comment by erikng** [comment]
There are still issues @tas50 

```
  * launchd[com.googlecode.munki.appusaged] action enable
    * file[/Library/LaunchDaemons/com.googlecode.munki.appusaged.plist] action create (up to date)
    * macosx_service[com.googlecode.munki.appusaged] action restart
      - restart service macosx_service[com.googlecode.munki.appusaged]
```

The resource is still restarting, but it seems like chef can't even detect the object is updating (as it's not green)

```
  * launchd[com.googlecode.munki.app_usage_monitor] action delete
    ================================================================================
    Error executing action `delete` on resource 'launchd[com.googlecode.munki.app_usage_monitor]'
    ================================================================================
    TypeError
    ---------
    no implicit conversion of nil into String
```

this screams to me idempotence is still broken

**Comment by erikng** [comment]
To replicate for the first case

```
## com.googlecode.munki.appusaged (3.3 and higher)
launchd 'com.googlecode.munki.appusaged' do
  label 'com.googlecode.munki.appusaged'
  program_arguments ['/usr/local/munki/appusaged']
  sockets(
    { 'appusaged' => {
      'SockPathName' => '/var/run/appusaged',
      'SockPathMode' => 438,
    } },
  )
  type 'daemon'
  action :enable
end
```

To replicate for the second
```
## com.googlecode.munki.app_usage_monitor - REMOVE (3.3 and higher)
launchd 'com.googlecode.munki.app_usage_monitor' do
  type 'daemon'
  action :delete
  only_if { node.min_package_installed?('com.googlecode.munki.app_usage', '3.3.0.3513') }
end
```

**Comment by lamont-granquist** [comment]
`manage_plist` used to return the updated status of the sub resource and use that to conditionally enable or restart the service resource.

that should probably be changed to a more sane chef pattern to have those subresources use a notification to the service resource to do a restart and then just call enable all the time.

**Comment by lamont-granquist** [comment]
@erikng i think that fixes all those issues.  unrelated, i fixed the problem where the `:disable` action would throw if the plist didn't exist.

**Comment by erikng** [comment]
Nice! Now we don't have to guard for that :)

**Comment by tas50** [comment]
we should get a backport to 15 for that one

**Comment by lamont-granquist** [comment]
Yeah I noticed that while writing the tests and figured that seemed like kinda shitty behavior...  If it ain't there at all its definitely disabled...
