### ISSUE TITLE
knife bootstrap winrm fails to bootstrap windows node

### ISSUE THREAD

**Issue by Trupti-bhansali** [chef/chef#9922]
## Description
bootstrap fails with " FATAL: Errno::EINVAL: Invalid argument @ dir_s_mkdir -"
command : knife bootstrap --channel current --bootstrap-version 16.1.15 -o winrm <IP_ADDRESS> -x <UserName> -P <'password'> -N <NodeName>

## Chef Version
Chef Workstation version: 0.18.3
Chef Infra Client version: 15.10.12

## Platform Version
Client -> Windows 2012 R2
Worstation -> Windows 10

## Replication Case
knife bootstrap --channel current --bootstrap-version 16.1.15 -o winrm <IP_ADDRESS> -x <UserName> -P <'password'> -N <NodeName>

## Client Output
[ip.ip.ip.ip] Detected Windows Version 6.3 Build 9600
 [ip.ip.ip.ip]
 [ip.ip.ip.ip] C:\Users\Administrator\Documents>goto Version6.3
 [ip.ip.ip.ip]
 [ip.ip.ip.ip] C:\Users\Administrator\Documents>goto architecture_select
 [ip.ip.ip.ip]
 [ip.ip.ip.ip] C:\Users\Administrator\Documents>IF "AMD64" == "x86" IF not defined PROCESSOR_ARCHITEW6432
 [ip.ip.ip.ip]
 [ip.ip.ip.ip] C:\Users\Administrator\Documents>goto chef_installed
 [ip.ip.ip.ip] Checking for existing Chef Infra Client installation
 [ip.ip.ip.ip]
 [ip.ip.ip.ip] C:\Users\Administrator\Documents>WHERE chef-client  1>nul 2>nul
 [ip.ip.ip.ip]
 [ip.ip.ip.ip] C:\Users\Administrator\Documents>If !ERRORLEVEL! == 0 (
 [ip.ip.ip.ip]
 [ip.ip.ip.ip]  goto key_create
 [ip.ip.ip.ip] )  else (
 [ip.ip.ip.ip]
 [ip.ip.ip.ip]  goto install
 [ip.ip.ip.ip] )
 [ip.ip.ip.ip] Existing Chef Infra Client installation detected, skipping download
 [54.172.18
1.219] Writing validation key...
 [ip.ip.ip.ip] Validation key written.
 [ip.ip.ip.ip]
 [i
 [ip.ip.ip.ip] C:\Users\Administrator\Documents>(echo.{"run_list":[]}) 1>C:\chef\first-boot.json
 [ip.ip.ip.ip] Starting chef-client to bootstrap the node...
 [ip.ip.ip.ip]
 [ip.ip.ip.ip] C:\Users\Administrator\Documents>SET "PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ruby\bin;C:\opscode\chef\chef\bin;C:\opscode\chef\chef\embedded\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\opscode\chef\bin\"
 [ip.ip.ip.ip]
 [ip.ip.ip.ip] C:\Users\Administrator\
Documents>chef-client -c C:\chef/client.rb -j C:\chef/first-boot.json

 [ip.ip.ip.ip] [2020-05-27T17:03:11+00:00] FATAL: Errno::EINVAL: Invalid argument @ dir_s_mkdir - C:/Users/Administrator/Documents

Aha! Link: https://chef.aha.io/features/SH-113

**Comment by Trupti-bhansali** [comment]
any help would appreciated?

**Comment by Vasu1105** [comment]
@Trupti-bhansali update your chef-workstation to current release https://downloads.chef.io/chef-workstation/current/20.5.53 and remove this `--channel current --bootstrap-version 16.1.15` from bootstrap command and try.. Looks like current release of chef-workstation this has been fixed https://github.com/chef/chef/issues/9844

**Comment by Trupti-bhansali** [comment]
@Vasu1105 I am using latest workstation 20.5.53.
> chef -v
Chef Workstation version: 20.5.53
Chef Infra Client version: 16.1.16
Chef InSpec version: 4.18.114
Chef CLI version: 3.0.1
Test Kitchen version: 2.5.1
Cookstyle version: 6.6.9

 But still getting same error:
[ip.ip.ip.ip] C:\Users\Administrator\Documents>(
 [ip.ip.ip.ip] echo.chef_server_url  "https://newchef.messagehub.rd.elliemae.io/organizations/newchef"
 [ip.ip.ip.ip]  echo.validation_client_name "newchef-validator"

 [ip.ip.ip.ip]  echo.file_cache_path   "C:\chef/cache"
 [ip.ip.ip.ip]  echo.file_backup_path  "C:\chef/backup"

 [ip.ip.ip.ip]  echo.cache_options     ({:path => "C:\chef/cache/checksums", :skip_expires => true})
 [ip.ip.ip.ip]  echo.chef_license "accept"
 [ip.ip.ip.ip]  echo.node_name "TruptiTestNode"
 [ip.ip.ip.ip]  echo.log_level        :auto
 [ip.ip.ip.ip]  echo.log_location       STDOUT

 [ip.ip.ip.ip]  echo.trusted_certs_dir "C:\chef/trusted_certs"
 [ip.ip.ip.ip] ) 1>C:\chef\client.rb

 [ip.ip.ip.ip]
 [ip.ip.ip.ip] C:\Users\Administrator\Documents>(echo.{"run_list":[]}) 1>C:\chef\first-boot.json

 [ip.ip.ip.ip] Starting chef-client to bootstrap the node...
 [ip.ip.ip.ip]

 [ip.ip.ip.ip] C:\Users\Administrator\Documents>SET "PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ruby\bin;C:\opscode\chef\bin;C:\opscode\chef\embedded\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\"
 [ip.ip.ip.ip]

 [ip.ip.ip.ip] C:\Users\Administrator\Documents>chef-client -c C:\chef/client.rb -j C:\chef/first-boot.json

 [ip.ip.ip.ip] [2020-05-29T09:43:22+00:00] FATAL: Errno::EINVAL: Invalid argument @ dir_s_mkdir - C:/Users/Administrator/Documentsef

ERROR: The following error occurred on ip.ip:

**Comment by Trupti-bhansali** [comment]
@Vasu1105 Any help would be appreciated!!

**Comment by KerenCohen** [comment]
We've also encountered the same issue...
 Any help would be highly appreciated!!

**Comment by purduerich** [comment]
I am having the exact same symptoms.  When I upgraded my workstation from 0.17.5 to 0.18.3 (then later 20.6.62), I started getting those exact same errors while bootstrapping a node.  Below is the boostrap command I've been using that works perfectly on 0.17.5 that now throws errors.

knife bootstrap -o winrm xxx.domain.local --winrm-user user --winrm-password 'pass' --node-name xxx.domain.local --policy-group xxx--policy-name yyyy


[xxx.domain.local] C:\Users\xxxx\Documents>chef-client -c C:\chef/client.rb -j C:\chef/first-boot.json
[xxx.domain.local] [2020-06-02T14:28:54-05:00] FATAL: Errno::EINVAL: Invalid argument @ dir_s_mkdir - C:/Users/xxxx/Documentsef
ERROR: The following error occurred on xxx.domain.local:
ERROR:

**Comment by mcascone** [comment]
same here:
```
Chef Workstation version: 20.6.62
Chef Infra Client version: 16.1.16
Chef InSpec version: 4.19.0
Chef CLI version: 3.0.4
Test Kitchen version: 2.5.1
Cookstyle version: 6.7.3
```

Error is:
```
[MLVTAREA32] C:\Users\hl_tfsbuild\Documents>chef-client -c C:\chef/client.rb -j C:\chef/first-boot.json -E MTP_QA
 [MLVTAREA32] [2020-06-11T14:50:39-05:00] FATAL: Errno::EINVAL: Invalid argument @ dir_s_mkdir - C:ef
ERROR: The following error occurred on MLVTAREA32:
ERROR:
```

look, the error is right there - it's not being escaped properly:
**C:\chef**/first-boot.json     --> Invalid argument @ dir_s_mkdir - **C:ef**

**Comment by tas50** [comment]
I've tried to reproduce this on master and I'm unable to get a failure. Master does have quite a few improvements that aren't yet in Workstation but we expect to have a release in of Chef Infra Client itself this week and ideally Workstation the week after.

Here's my test output:

```
bundle exec knife bootstrap 52.25.94.50 --connection-protocol winrm --user Administrator
Connecting to 52.25.94.50 using winrm
WARNING: Failed to authenticate  to 52.25.94.50 - trying password auth
Enter password for @52.25.94.50:

Connecting to 52.25.94.50 using winrm
WARNING: Performing legacy client registration with the validation key at /Users/tsmith/.chef/tim_smith-validator.pem...
WARNING: Remove the key file or remove the 'validation_key' configuration option from your config.rb (knife.rb) to use more secure user credentials for client registration.
Bootstrapping 52.25.94.50
 [52.25.94.50] Checking for existing directory "C:\chef"...
 [52.25.94.50] Existing directory found, skipping creation.
 [52.25.94.50]
 [52.25.94.50] C:\Users\Administrator\Documents>(
 [52.25.94.50] echo.url = WScript.Arguments.Named("url")
 [52.25.94.50]  echo.path = WScript.Arguments.Named("path")
 [52.25.94.50]  echo.proxy = null
 [52.25.94.50]  echo.'* Vaguely attempt to handle file:// scheme urls by url unescaping and switching all
 [52.25.94.50]  echo.'* / into .  Also assume that file:/// is a local absolute path and that file://<foo>
 [52.25.94.50]  echo.'* is possibly a network file path.
 [52.25.94.50]  echo.If InStr(url, "file://") = 1 Then
 [52.25.94.50]  echo.url = Unescape(url)
 [52.25.94.50]  echo.If InStr(url, "file:///") = 1 Then
 [52.25.94.50]  echo.sourcePath = Mid(url, Len("file:///") + 1)
 [52.25.94.50]  echo.Else
 [52.25.94.50]  echo.sourcePath = Mid(url, Len("file:") + 1)
 [52.25.94.50]  echo.End If
 [52.25.94.50]  echo.sourcePath = Replace(sourcePath, "/", "\")
 [52.25.94.50]  echo.
 [52.25.94.50]  echo.Set objFSO = CreateObject("Scripting.FileSystemObject")
 [52.25.94.50]  echo.If objFSO.Fileexists(path) Then objFSO.DeleteFile path
 [52.25.94.50]  echo.objFSO.CopyFile sourcePath, path, true
 [52.25.94.50]  echo.Set objFSO = Nothing
 [52.25.94.50]  echo.
 [52.25.94.50]  echo.Else
 [52.25.94.50]  echo.Set objXMLHTTP = CreateObject("MSXML2.ServerXMLHTTP")
 [52.25.94.50]  echo.Set wshShell = CreateObject( "WScript.Shell" )
 [52.25.94.50]  echo.Set objUserVariables = wshShell.Environment("USER")
 [52.25.94.50]  echo.
 [52.25.94.50]  echo.rem http proxy is optional
 [52.25.94.50]  echo.rem attempt to read from HTTP_PROXY env var first
 [52.25.94.50]  echo.On Error Resume Next
 [52.25.94.50]  echo.
 [52.25.94.50]  echo.If NOT (objUserVariables("HTTP_PROXY") = "") Then
 [52.25.94.50]  echo.proxy = objUserVariables("HTTP_PROXY")
 [52.25.94.50]  echo.
 [52.25.94.50]  echo.rem fall back to named arg
 [52.25.94.50]  echo.ElseIf NOT (WScript.Arguments.Named("proxy") = "") Then
 [52.25.94.50]  echo.proxy = WScript.Arguments.Named("proxy")
 [52.25.94.50]  echo.End If
 [52.25.94.50]  echo.
 [52.25.94.50]  echo.If NOT isNull(proxy) Then
 [52.25.94.50]  echo.rem setProxy method is only available on ServerXMLHTTP 6.0+
 [52.25.94.50]  echo.Set objXMLHTTP = CreateObject("MSXML2.ServerXMLHTTP.6.0")
 [52.25.94.50]  echo.objXMLHTTP.setProxy 2, proxy
 [52.25.94.50]  echo.End If
 [52.25.94.50]  echo.
 [52.25.94.50]  echo.On Error Goto 0
 [52.25.94.50]  echo.
 [52.25.94.50]  echo.objXMLHTTP.open "GET", url, false
 [52.25.94.50]  echo.objXMLHTTP.send()
 [52.25.94.50]  echo.If objXMLHTTP.Status = 200 Then
 [52.25.94.50]  echo.Set objADOStream = CreateObject("ADODB.Stream")
 [52.25.94.50]  echo.objADOStream.Open
 [52.25.94.50]  echo.objADOStream.Type = 1
 [52.25.94.50]  echo.objADOStream.Write objXMLHTTP.ResponseBody
 [52.25.94.50]  echo.objADOStream.Position = 0
 [52.25.94.50]  echo.Set objFSO = Createobject("Scripting.FileSystemObject")
 [52.25.94.50]  echo.If objFSO.Fileexists(path) Then objFSO.DeleteFile path
 [52.25.94.50]  echo.Set objFSO = Nothing
 [52.25.94.50]  echo.objADOStream.SaveToFile path
 [52.25.94.50]  echo.objADOStream.Close
 [52.25.94.50]  echo.Set objADOStream = Nothing
 [52.25.94.50]  echo.End If
 [52.25.94.50]  echo.Set objXMLHTTP = Nothing
 [52.25.94.50]  echo.End If
 [52.25.94.50] ) 1>C:\chef\wget.vbs
 [52.25.94.50]
 [52.25.94.50] C:\Users\Administrator\Documents>(
 [52.25.94.50] echo.param(
 [52.25.94.50]  echo.   [String] $remoteUrl,
 [52.25.94.50]  echo.   [String] $localPath
 [52.25.94.50]  echo.)
 [52.25.94.50]  echo.
 [52.25.94.50]  echo.$ProxyUrl = $env:http_proxy;
 [52.25.94.50]  echo.$webClient = new-object System.Net.WebClient;
 [52.25.94.50]  echo.
 [52.25.94.50]  echo.if ($ProxyUrl -ne '') {
 [52.25.94.50]  echo.  $WebProxy = New-Object System.Net.WebProxy($ProxyUrl,$true)
 [52.25.94.50]  echo.  $WebClient.Proxy = $WebProxy
 [52.25.94.50]  echo.}
 [52.25.94.50]  echo.
 [52.25.94.50]  echo.$webClient.DownloadFile($remoteUrl, $localPath);
 [52.25.94.50] ) 1>C:\chef\wget.ps1
 [52.25.94.50]
 [52.25.94.50] C:\Users\Administrator\Documents>(
 [52.25.94.50]
 [52.25.94.50]
 [52.25.94.50]
 [52.25.94.50] )
 [52.25.94.50] Detected Windows Version 10.0 Build 17763
 [52.25.94.50]
 [52.25.94.50] C:\Users\Administrator\Documents>goto Version10.0
 [52.25.94.50]
 [52.25.94.50] C:\Users\Administrator\Documents>goto architecture_select
 [52.25.94.50]
 [52.25.94.50] C:\Users\Administrator\Documents>IF "AMD64" == "x86" IF not defined PROCESSOR_ARCHITEW6432
 [52.25.94.50]
 [52.25.94.50] C:\Users\Administrator\Documents>goto chef_installed
 [52.25.94.50] Checking for existing Chef Infra Client installation
 [52.25.94.50]
 [52.25.94.50] C:\Users\Administrator\Documents>WHERE chef-client  1>nul 2>nul
 [52.25.94.50]
 [52.25.94.50] C:\Users\Administrator\Documents>If !ERRORLEVEL! == 0 (
 [52.25.94.50]
 [52.25.94.50]  goto key_create
 [52.25.94.50] )  else (
 [52.25.94.50]
 [52.25.94.50]  goto install
 [52.25.94.50] )
 [52.25.94.50] No existing installation of Chef Infra Client detected
 [52.25.94.50] Checking for existing downloaded package at "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
 [52.25.94.50] Found existing downloaded package, deleting.
 [52.25.94.50] Attempting to download client package using PowerShell if available...
 [52.25.94.50] powershell.exe -ExecutionPolicy Unrestricted -InputFormat None -NoProfile -NonInteractive -File  C:\chef\wget.ps1 "https://www.chef.io/chef/download?p=windows&pv=2016&m=x86_64&DownloadContext=PowerShell&channel=stable&v=16" "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
 [52.25.94.50] Download via PowerShell succeeded.
 [52.25.94.50] Installing downloaded client package...
 [52.25.94.50]
 [52.25.94.50] C:\Users\Administrator\Documents>msiexec /qn /log "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-msi20619.log" /i "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
 [52.25.94.50] Successfully installed Chef Infra Client package.
 [52.25.94.50] Installation completed successfully
 [52.25.94.50] Writing validation key...
 [52.25.94.50] Validation key written.
 [52.25.94.50]
 [52.25.94.50] C:\Users\Administrator\Documents>(
 [52.25.94.50] echo.-----BEGIN CERTIFICATE-----
 [52.25.94.50]  echo.-----END CERTIFICATE-----
 [52.25.94.50] ) 1>C:\chef/trusted_certs/34_213_52_193.crt
 [52.25.94.50]
 [52.25.94.50] C:\Users\Administrator\Documents>(
 [52.25.94.50] echo.chef_server_url  "https://api.chef.io/organizations/tim_smith"
 [52.25.94.50]  echo.validation_client_name "tim_smith-validator"
 [52.25.94.50]  echo.file_cache_path   "C:/chef/cache"
 [52.25.94.50]  echo.file_backup_path  "C:/chef/backup"
 [52.25.94.50]  echo.cache_options     ({:path => "C:/chef/cache/checksums", :skip_expires => true})
 [52.25.94.50]  echo.chef_license "accept"
 [52.25.94.50]  echo.# Using default node name (fqdn)
 [52.25.94.50]  echo.log_level        :auto
 [52.25.94.50]  echo.log_location       STDOUT
 [52.25.94.50]  echo.trusted_certs_dir "C:/chef/trusted_certs"
 [52.25.94.50] ) 1>C:\chef\client.rb
 [52.25.94.50]
 [52.25.94.50] C:\Users\Administrator\Documents>(echo.{"run_list":[]}) 1>C:\chef\first-boot.json
 [52.25.94.50] Starting chef-client to bootstrap the node...
 [52.25.94.50]
 [52.25.94.50] C:\Users\Administrator\Documents>SET "PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ruby\bin;C:/opscode/chef\bin;C:/opscode/chef\embedded\bin;C:\tools\ruby27\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Amazon\cfn-bootstrap\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps"
 [52.25.94.50]
 [52.25.94.50] C:\Users\Administrator\Documents>chef-client -c C:/chef/client.rb -j C:/chef/first-boot.json
 [52.25.94.50] Starting Chef Infra Client, version 16.1.16
 [52.25.94.50] Creating a new client identity for EC2AMAZ-3SCR1KK.us-west-2.compute.internal using the validator key.
 [52.25.94.50] resolving cookbooks for run list: []
 [52.25.94.50] Synchronizing Cookbooks:
 [52.25.94.50] Installing Cookbook Gems:
 [52.25.94.50] Compiling Cookbooks...
 [52.25.94.50] [2020-06-16T23:10:13+00:00] WARN: Node EC2AMAZ-3SCR1KK.us-west-2.compute.internal has an empty run list.
 [52.25.94.50] Converging 0 resources
 [52.25.94.50]
 [52.25.94.50] Running handlers:
 [52.25.94.50] Running handlers complete
 [52.25.94.50] Chef Infra Client finished, 0/0 resources updated in 11 seconds
```
My flags are a bit different since I'm using the new Chef 15+ flags to avoid deprecation warnings. Additionally, I'd avoid using -P since that displays your password. Knife will prompt you automatically for the password

**Comment by dheerajd-msys** [comment]
@tas50 this issue is getting reproduced on Windows---->Windows bootstrap process. From your results, it seems you are trying to bootstrap from Linux--->Windows. Could you please check once?

Thank you!!

**Comment by mcascone** [comment]
@tas have you been able to take another look at this? it's a blocker for us.

**Comment by tas50** [comment]
@mcascone This is being worked on now

**Comment by jainSachin8** [comment]
Having same issue, any solution yet?

**Comment by kethahel99** [comment]
Hello, is this fixed. It is a big problem. Which chef-client version stable that can we use in the meantime?

**Comment by dheerajd-msys** [comment]
For reference https://github.com/chef/chef/pull/10141#issuecomment-665080902

**Comment by mcascone** [comment]
I keep getting a notification to update to 20.8.111, but it doesn't look like this is fixed yet?

**Comment by aswinfrancis91** [comment]
```
 [2020-08-14T11:30:20+00:00] FATAL: Errno::EINVAL: Invalid argument @ dir_s_mkdir - C:/Users/chef/Documentsef
ERROR: The following error occurred on chef-lab-hcniui.westus.cloudapp.azure.com:
ERROR: cmd.exe : Exception calling "DownloadFile" with "2" argument(s): "The request was
         + CategoryInfo          : NotSpecified: (Exception calli...he request was :String) [], RemoteException
         + FullyQualifiedErrorId : NativeCommandError
     aborted: Could not create SSL/TLS secure channel."
     At C:\chef\wget.ps1:14 char:1
     + $webClient.DownloadFile($remoteUrl, $localPath);
     + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
         + FullyQualifiedErrorId : WebException

     Failed download: download completed, but downloaded file not found

```
I get this when I run 
`knife bootstrap -o winrm *fqdn*  -u *username*-P *password* -N windows-client --verbose`

If I run it again, i get
```
[2020-08-14T11:57:55+00:00] FATAL: Errno::EINVAL: Invalid argument @ dir_s_mkdir - C:/Users/chef/Documentsef
ERROR: The following error occurred on ****:
ERROR:
```

**Comment by dheerajd-msys** [comment]
This is being addressed in https://github.com/chef/chef/pull/10298 and I've tested of it's working for **_windows-to-windows_** bootstrap.

**Comment by aswinfrancis91** [comment]
Using the latest client version 16.4.35. Now i get similar error

 [2020-08-18T10:59:42+00:00] FATAL: Errno::EINVAL: Invalid argument @ dir_s_mkdir - C:/windows/system32ef

**Comment by dheerajd-msys** [comment]
@aswinfrancis91 Please check if there is anything other than 16.4.35 is installed, Update your GEM_PATH, GEM_HOME, and PATH variables per v16.4.35.

**Comment by mwrock** [comment]
I ran into this as well. I believe this is addressed in an upcoming version but even if you are using the "fixed" version, you will continue to tun into this problem if you are trying to bootstrap the same node that previously failed if that node has the `client.rb` file from the previous boostrap. The issue is the backslashes in that file. You should be good if you uninstall any chef client install that might be on that node along with the `c:\chef` directory.

**Comment by kethahel99** [comment]
I have the same experience. I have to fix the slashes kn the client.rb file manually and rerun chef-client, whether older or newest version of the client. . Which is the upcoming workstation version where this will be fixed?

**Comment by dheerajd-msys** [comment]
This is fixed in https://github.com/chef/chef/pull/10298 and shipped in `Chef Infra Client v16.4.35` and `Chef workstation v20.8.125`
Tested with both successfully.
